openapi: "3.1.3"

info:
  title: "TODOアプリAPI"
  version: "1.0.0"

servers:
- url: "http://localhost:3001"
  description: "local environment"

tags:
- name: "todo"
  description: "TODOアプリのタスクに関するAPI"

paths: 
  "/todos":
    get:
      summary: "TODO一覧取得API"
      tags: ["todo"]        
      deprecated: false
      responses:
        "200":
          description: "TODO一覧取得成功"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      summary: "TODO登録API"
      deprecated: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: "TODO Name"
                  example: "homework"
  "/todos/{id}":
    patch:
      summary: "TODOタスクの完了API"
      deprecated: false
    delete:
      summary: "TODO削除API"
      deprecated: false

components:
  schemas:
    Todo:
      type: object
      properties:
        id: { type: number, example: 1 }
        text: { type: string, example: user }
        completed: { type: bool, example: true }      